# -*- coding: utf-8 -*-
"""Assignment-1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J9dPK9rhcImwE-qMghRFsZVIX9wZzUQG
"""

def OddOrEven(num):
#logic =when we devide even number with 2 it will give remainder zero otherwise it is odd
 if num%2==0:
   print("it is even number")
 else:
        print("it is odd number")

OddOrEven(3)

OddOrEven(8)

OddOrEven(176)

OddOrEven(1953)

6